### PR TITLE
updated instructions for m1

### PR DESCRIPTION
**Pull request by exshak**
Added support for downloading apple aarch64 binary (for m1).

### CODE REVIEW

**Comment by tzachar** [comment]
I don't have a mac to check this. Did you verify it is working on an M1 and an older mac?

**Comment by exshak** [comment]
Works on an M1 MacBook (v11.4). I haven't tested it on an Intel mac but it should default to previous behaviour as "arm64" will be M1 respective.

**Comment by tzachar** [comment]
Can you find some one to test it on an Intel Mac?

**Comment by exshak** [comment]
I'll report back once I have confirmation it works on Intel mac's.

**Comment by exshak** [comment]
Working on Intel mac's (mac mini).

**Pull request merged**
